# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.cache/wt [current_project]
set_property parent.project_path C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/naomi/AppData/Roaming/Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/sources_1/new/conv_unit.sv
  C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/sources_1/new/image_array_to_uart.sv
  C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/sources_1/new/uart_to_image_array.sv
  C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/sources_1/new/conv_top_test.sv
  C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/sources_1/new/conv_block.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/sources_1/new/uart_receiver.v
  C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/sources_1/new/baud_rate_generator.v
  C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/sources_1/new/fifo.v
  C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/sources_1/new/uart_top.v
  C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/sources_1/new/debounce_explicit.v
  C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/sources_1/new/uart_transmitter_new.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/constrs_1/imports/CSE100/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/naomi/Documents/Personal-Projects/edge_detection/edge_detection.srcs/constrs_1/imports/CSE100/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top convolution_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef convolution_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file convolution_top_utilization_synth.rpt -pb convolution_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
